### DISCUSSION TITLE
Deploying foxglove_bridge with Docker Swarm

### DISCUSSION THREAD

**Discussion by peterdavidfagan** [foxglove/community#859] [General]
I am looking to deploy `foxglove_bridge` within a docker container. I couldn't find details of `foxglove_bridge` deployments from containers, posting question here in case there is a standard deployment config.

**Current Application Deployment Config**
```yaml
version: "3"

services: 
  control_server:
    image: ghcr.io/ipab-rad/lite6_control:rolling
    build: 
      context: ../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_control_demos control_server.launch.py # replace with command for specific tutorial
    deploy:
      restart_policy: 
        condition: any
      placement:
        constraints:
          - node.hostname == robot
          
  servo:
    image: ghcr.io/ipab-rad/lite6_control:rolling
    build: 
      context: ../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_control_demos servo_pose_jtc.launch.py # replace with command for specific tutorial
    deploy:
      restart_policy: 
        condition: any
      placement:
        constraints:
          - node.hostname == robot

  foxglove:
    image: ghcr.io/foxglove/studio:latest
    network_mode: "host"
    deploy:
      placement:
        constraints:
          - node.hostname == thor
  
  foxglove_bridge:
    image: ghcr.io/foxglove/rolling-ros2-bridge:latest
    network_mode: "host"
    deploy:
      placement:
        constraints:
          - node.hostname == thor

```

**Console Output**
```
control-foxglove_bridge-1  | terminate called after throwing an instance of 'std::bad_alloc'
control-foxglove_bridge-1  |   what():  std::bad_alloc
control-foxglove_bridge-1  | [ros2run]: Aborted
control-foxglove_bridge-1 exited with code 250
```

For now I am deploying the bridge locally before deploying the application this works well.
