### DISCUSSION TITLE
Fix cache in Foxglove Studio

### DISCUSSION THREAD

**Discussion by rafal-gorecki** [foxglove/community#876] [Show & Tell]
Hello,

Our team has identified an issue with the latest Docker image ghcr.io/foxglove/studio:latest (version 1.76.0). When running the image twice on the same machine with a modified default-layout.yaml, the layout does not update unless a new Chrome instance is opened in incognito mode. We've made some enhancements to your Docker image to address this issue, and we'd like to share our solution to assist in the development of your application.

### I. Empty Layout
1. Create `compose.yaml`
```yaml
services:
  foxglove:
    image: ghcr.io/foxglove/studio:latest
    ports:
      - 8080:8080
    # volumes:
    #   - ./foxglove_layout.json:/foxglove/default-layout.json

  foxglove-datasource:
    image: husarion/foxglove-bridge:humble
    ports:
      - 8765:8765
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,connectionGraph,assets]
```

2. Run the compose (`docker compose up`)
3. Open Chrome, navigate to `localhost:8080`, and click "Open connection" with "Foxglove WebSocket".

**Result: You should see an empty layout.**

### II. Custom layout
1. Close Docker containers (`docker compose down`)
2. Add [foxglove_layout.json](https://github.com/husarion/rosbot-sensors/blob/main/config/foxglove_layout.json) and uncomment the `volumes` section in the compose file.
3. Run the compose (`docker compose up`)
4. Reload Chrome at `localhost:8080` in Chrome.

**Result: You should see an empty layout.**

5. Open  Chrome in incognito mode and type `localhost:8080`. 

**Result: The correct Foxglove layout should now be displayed.**

## Our solution:
We have addressed this issue in our [foxglove-docker](https://github.com/husarion/foxglove-docker) repository using the `ENTRYPOINT `directive. You can test our solution by following the steps outlined above with [our compose file](https://github.com/husarion/foxglove-docker/blob/main/demo/compose.foxglove_bridge.yaml). 
We kindly share this change and ask you to include this change in the official Foxglove Docker image for a smoother user experience.

Best regards,
Rafał Górecki
Husarion
